version: "3.4"
services:
  pinyincardapi:
    image: pinyincardapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  mysql:
    container_name: pinyin_card_mysql
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql:rw,delegated
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      SERVICE_NAME: "pinyin-card-mysql"
      TZ: "America/Sao_Paulo"
    ports:
      - "33061:3306"
